name: bq-redeploy
on:
  workflow_dispatch:

jobs:
  connect:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

      - name: set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

      - name: Read buckets
        shell: bash
        run: |
          file="bq/query.sql"

          
          query_validation=$(bq query --dry_run --use_legacy_sql=false --format=csv < "$file")
          echo "$query_validation"
          echo "No corrio"

          
          if [[ "$query_validation" =~ ^[0-9]+$ ]]; then
            echo "It works"
          else
            echo "$file: $query_validation"
            exit 1
          fi
