name: bq-redeploy

on:
  workflow_dispatch:
    inputs:
        files:
          required: true
          type: string
          description: "Files to re-deploy"
jobs:
  connect:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

      - name: set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"


      - name: BQ Re-Deployment
        run: |

          path_files=""
          echo "Files not founded" >> $GITHUB_STEP_SUMMARY

          IFS=',' read -ra file_array <<< "$(echo "${{ github.event.inputs.files }}" | tr -d ' ')"
          
          for file in "${file_array[@]}"; do
            file_no_spaces=$(echo "$file" | tr -d ' ')

            path=$(find tir-bigquery/ -type f -name "$file_no_spaces.sql")

            if [ -z $path ]; then
              echo "#### $file_no_spaces is not founded" >> $GITHUB_STEP_SUMMARY
            else
              if [ -z $path_files ]; then
                path_files="$path"
              else
                path_files="$path_files,$path"
              fi
            fi
          done
        
          pip install -r .github/workflows/requirements.txt
          errors=$(python .github/workflows/bq_deploy.py --env="dev" --configs="project_id=telus-tir-project" --location="us" --files="$path_files")
          echo "$errors" >> $GITHUB_STEP_SUMMARY
