name: 02. Shutdown Composer

on:
  workflow_dispatch:
  
permissions: write-all

jobs:
  review:
    name: Review Execution
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.master_variables.outputs.environment }}
      composer_environment_name: ${{ steps.master_variables.outputs.composer_environment_name }}
      composer_gcs_bucket: ${{ steps.master_variables.outputs.composer_gcs_bucket }}
      region: ${{ steps.master_variables.outputs.region }}
      master_dag: ${{ steps.master_variables.outputs.master_dag }}
      master_dag_wait: ${{ steps.master_variables.outputs.master_dag_wait }}
      master_dag_timeout: ${{ steps.master_variables.outputs.master_dag_timeout }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Retrieve variables from master.json
      uses: ./.github/actions/master-variables
      id: master_variables

    - name: Add details to job summary
      shell: bash
      run: |
        echo "This job will **shutdown Composer in ${{ steps.master_variables.outputs.environment }}** environment " >> $GITHUB_STEP_SUMMARY
        echo "Before destroying composer, a snapshot will be saved and its path saved in Github variable: **LATEST_SNAPSHOT_PATH**" >> $GITHUB_STEP_SUMMARY
        
        echo "#### DETAILS " >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ steps.master_variables.outputs.environment }} " >> $GITHUB_STEP_SUMMARY
        echo "**Terraform project folder:** ${{ env.PROJECT_DIRECTORY }} " >> $GITHUB_STEP_SUMMARY
        echo "**Terraform tfvars file (relative to project folder):** ../../${{ steps.master_variables.outputs.environment }}.tfvars " >> $GITHUB_STEP_SUMMARY
        echo "**Terraform modules/resources that will be affected:** " >> $GITHUB_STEP_SUMMARY
        echo "- module.composer" >> $GITHUB_STEP_SUMMARY
        echo "- null_resource.set_airflow_variables" >> $GITHUB_STEP_SUMMARY


  composer:
    name: Shutdown Composer Environment
    needs: review
    environment: ${{ needs.review.outputs.environment }} #it will require approval if the environment has deployment rules configured
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    timeout-minutes: 90
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Shutdown composer environment
      uses: ./.github/actions/composer-deployment
      with:
        environment: ${{ needs.review.outputs.environment }}
        gcp-workload-identity-provider: ${{ secrets.PROVIDER_NAME }}
        gcp-service-account: ${{ secrets.SA_EMAIL }}
        action: destro
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        targets: ${{ env.TARGETS }}
        var-file: ../../${{ needs.review.outputs.environment }}.tfvars
        composer-environment-name: ${{ needs.review.outputs.composer_environment_name }}
        composer-gcs-bucket: ${{ needs.review.outputs.composer_gcs_bucket }}
        composer-location: ${{ needs.review.outputs.region }}
        github-token: ${{ secrets.TH_BOT_PAT }}
        master-dag: ${{ needs.review.outputs.master_dag }}
        master-dag-wait: ${{ needs.review.outputs.master_dag_wait }}
        master-dag-timeout: ${{ needs.review.outputs.master_dag_timeout }}
