name: Composer Dags Deploy

on:
  workflow_dispatch:
    inputs:
    
      dags_to_deploy:
        description: "Enter * to deploy all DAGs. Otherwise provide a comma separated list of DAG names to deploy. Master DAG is always deployed."
        required: true
        type: string

jobs:
  deploy-dags:
  
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    
    steps:

      - name: Validate input parameters
        id: validate-deploy-inputs
        run: |
          
          DAGS_TO_DEPLOY=${{ github.event.inputs.dags_to_deploy }}

          if [[ "$DAGS_TO_DEPLOY" == "*" ]]; then
            echo "All DAGs will be deployed."
            echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> $GITHUB_OUTPUT

          else
            # Regex to validate the input string
            regex="^([a-zA-Z0-9_]+)(,[a-zA-Z0-9_]+)*$"

            if ! [[ "$DAGS_TO_DEPLOY" =~ $regex ]]; then
              echo "::error::Input string contains invalid characters or format. Only alphanumeric and underscore characters are allowed. Values must be comma-separated with no whitespaces."
              exit 1
            else
              echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> "$GITHUB_OUTPUT"
            fi

          fi
      
      - name: Take Git reference
        id: get-gitref
        run: |
          base=$(basename "${{ github.ref }}")
          sh_short=$(echo "${{ github.sha }}" | cut -c1-7)
        
          if [[ "${{ github.ref }}" == *"tags"* ]]; then
            ref="$base"
          else
            ref="$base-$sh_short"
          fi
          
          echo "git_ref=$ref" >> $GITHUB_OUTPUT
          echo "base_ref=$base" >> $GITHUB_OUTPUT


      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-gitref.outputs.base_ref }}


      - name: Retrieve variables from master.json
        id: master-variables
        uses: ./.github/actions/master-variables


      - name: Google Cloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

      - name: Set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"


      - name: Deploy DAGs
        id: deployscript
        run: |
          
          echo "Fetching Airflow DAG Versions variable"
          FLAG_CREATE_DAGS_VS="false"
          CURRENT_DAGS_VS=$(gcloud composer environments run ${{ steps.master-variables.outputs.composer_environment_name }} --location=${{ steps.master-variables.outputs.region }} variables get -- dags_version 2>&1) || \
          CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines

          # Handle variable not existing sceneario
          if [[ "$CURRENT_DAGS_VS" == *"Variable dags_version does not exist"* ]]; then
            echo "::warning::Variable dags_version did not exist in Airflow environment. This process will recreate it. If this is not your first run review why it has been deleted."
            # Create var with dags vs being deployed
            
            FLAG_CREATE_DAGS_VS="true"

          else
            CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines
            if [[ "$CURRENT_DAGS_VS" == *"{"*"}"* ]]; then # If response matches a JSON format {}
              echo "Found current DAGs version: $CURRENT_DAGS_VS" # Variable exists, get the output
            else
              echo "::error::gcloud command failed: $CURRENT_DAGS_VS" # gcloud command failed for a different reason
              exit 1
            fi

          fi


          # Get new version and file to process.
          DAG_ID_SUFFIX=${{ steps.get-gitref.outputs.git_ref }}
          echo "DAGs will be added suffix: $DAG_ID_SUFFIX"
          DAG_LIST=${{ steps.validate-deploy-inputs.outputs.dags_to_deploy }}
          echo "DAGs to deploy: $DAG_LIST"

          # Find path DAGs to process
          search_dir="$GITHUB_WORKSPACE/composer"
          found_dags=()
          versioned_dags_to_deploy=()


          if [[ "$DAG_LIST" == '*' ]]; then
            for file in $(find "$search_dir" -type f -path "*/dags/*.py"); do
              filename=$(basename "$file" .py)
              found_dags+=("$filename") # Append the found file to the array
            done
          else
            IFS=',' read -ra dags_to_deploy <<< "$DAG_LIST" # Convert comma-separated string to an array
            # Iterate through the array
            for item in "${dags_to_deploy[@]}"; do
              # Search for files with the given name and .py extension recursively
              for file in $(find "$search_dir" -type f -path "*/${item}/dags/${item}.py"); do
                filename=$(basename "$file" .py)
                found_dags+=("$filename") # Append the found file to the array
              done
            done
          fi


          echo "$found_dags"

          
          
      - name: Print
        run: |
          echo "${{ steps.validate-deploy-inputs.outputs.dags_to_deploy }}"
          echo "${{ steps.get-gitref.outputs.git_ref }}"
          
