name: connect_gcp
on:
  workflow_dispatch:

jobs:
  connect:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          files="StgProvideraaa, StgProvider"

          # Convert the string to an array
          IFS=',' read -ra file_array <<< "$(echo "$files" | tr -d ' ')"
          
          # Iterate through the array using a for loop
          for file in "${file_array[@]}"; do
            string_no_spaces=$(echo "$file" | tr -d ' ')
            echo $string_no_spaces
          done
                    
          
                    
