name: connect_gcp
on:
  workflow_dispatch:

jobs:
  connect:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          files="StgProvideraaa, StgProvider"

          IFS=',' read -ra file_array <<< "$(echo "$files" | tr -d ' ')"
          
          for file in "${file_array[@]}";
            echo "$file"
          done
                    
          
          
                    
