name: Airflow DAGs Deploy

on:
  workflow_dispatch:
    inputs:

      deploy_tag:
        description: "Git Tag to deploy"
        required: false
        type: string

      deploy_branch:
        description: "Branch to deploy if no tag was provided"
        required: false
        type: string

      dags_to_deploy:
        description: "Enter * to deploy all DAGs. Otherwise provide a comma separated list of DAG names to deploy. Master DAG is always deployed."
        required: true
        type: string

  
jobs:
  deploy-dags:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Validate input parameters
        id: validate-deploy-inputs
        run: |
          if [[ -z "${{ github.event.inputs.deploy_tag }}" && -z "${{ github.event.inputs.deploy_branch }}" ]]; then
            echo "::error::Either deploy_tag or deploy_branch must be provided."
            exit 1
          fi

          DAGS_TO_DEPLOY=${{ github.event.inputs.dags_to_deploy }}

          if [[ "$DAGS_TO_DEPLOY" == "*" ]]; then
            echo "All DAGs will be deployed."
            echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> $GITHUB_OUTPUT

          else
            # Regex to validate the input string
            regex="^([a-zA-Z0-9_]+)(,[a-zA-Z0-9_]+)*$"

            if ! [[ "$DAGS_TO_DEPLOY" =~ $regex ]]; then
              echo "::error::Input string contains invalid characters or format. Only alphanumeric and underscore characters are allowed. Values must be comma-separated with no whitespaces."
              exit 1

            else
              echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> "$GITHUB_OUTPUT"
            
            fi

          fi


      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_tag || github.event.inputs.deploy_branch }}


      - name: Select git reference to deploy
        id: deployref
        run: |
          echo "Selected git reference: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          DEPLOY_TAG=${{ github.event.inputs.deploy_tag }}
            
          if [[ "$DEPLOY_TAG" != "" ]]; then
            echo "DAG IDs will be concatenated with tag: $DEPLOY_TAG"
            echo "dags_concat_id=$DEPLOY_TAG" >> $GITHUB_OUTPUT
          
          else
            SHORTSHA=$(git rev-parse --short ${{ github.sha }})
            echo "Will deploy latest changes at branch: ${{ github.event.inputs.deploy_branch }}"
            echo "DAG IDs will be concatenated with short SHA from commit: $SHORTSHA"
            echo "dags_concat_id=$SHORTSHA" >> $GITHUB_OUTPUT
          fi


      - name: Retrieve variables from master.json
        id: master_variables
        uses: ./.github/actions/master-variables

      - name: Google Cloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

      - name: Set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"


      - name: Deploy DAGs
        id: deployscript
        run: |

          echo "Fetching Airflow DAG Versions variable"
          FLAG_CREATE_DAGS_VS="false"
          CURRENT_DAGS_VS=$(gcloud composer environments run ${{ steps.master_variables.outputs.composer_environment_name }} --location=${{ steps.master_variables.outputs.region }} variables get -- dags_version 2>&1) || \
          CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines

          # Handle variable not existing sceneario
          if [[ "$CURRENT_DAGS_VS" == *"Variable dags_version does not exist"* ]]; then
            echo "::warning::Variable dags_version did not exist in Airflow environment. This process will recreate it. If this is not your first run review why it has been deleted."
            # Create var with dags vs being deployed
            
            FLAG_CREATE_DAGS_VS="true"

          else          
            if [[ $? -ne 0 ]]; then
              echo "::error::gcloud command failed: $CURRENT_DAGS_VS" # gcloud command failed for a different reason
              exit 1
              
            else
              echo "$CURRENT_DAGS_VS" # Variable exists, get the output
              
            fi

          fi

          DAG_ID_SUFFIX=${{ steps.deployref.outputs.dags_concat_id }}
          echo "DAGs will be added suffix: $DAG_ID_SUFFIX"
          DAG_LIST=${{ steps.validate-deploy-inputs.outputs.dags_to_deploy }}
          echo "DAGs to deploy: $DAG_LIST"


          search_dir="$GITHUB_WORKSPACE/composer"
          found_dags=()
          versioned_dags_to_deploy=()

          if [[ "$DAG_LIST" == '*' ]]; then
            for file in $(find "$search_dir" -type f -path "*/dags/*.py"); do
              filename=$(basename "$file" .py)
              found_dags+=("$filename") # Append the found file to the array
            done

          else
            IFS=',' read -ra dags_to_deploy <<< "$DAG_LIST" # Convert comma-separated string to an array
            # Iterate through the array
            for item in "${dags_to_deploy[@]}"; do
              # Search for files with the given name and .py extension recursively
              for file in $(find "$search_dir" -type f -path "*/${item}/dags/${item}.py"); do
                filename=$(basename "$file" .py)
                found_dags+=("$filename") # Append the found file to the array
              done
            done

          fi

          echo "DAGs found in repo"
          echo "${found_dags[@]}" # Space separated list

          # Iterate through the array of found dags to add deploy-specific ID
          if [[ ${#found_dags[@]} -gt 0 ]]; then
              for found_dag in "${found_dags[@]}"; do
                  versioned_dags_to_deploy+=("${found_dag}_${DAG_ID_SUFFIX}")
              done
          else
              echo "::error::No matching DAG files found. Review your repository files"
              exit 1
          fi

          echo "DAGs will be deployed as:"
          echo "${versioned_dags_to_deploy[@]}" # Space separated list

          if [[ "$FLAG_CREATE_DAGS_VS" == "true" ]]; then 
            echo "Create dags version var"

          else
            echo "Update dags version var"

          fi