name: Airflow DAGs Deploy

on:
  workflow_dispatch:
    inputs:

      deploy_tag:
        description: "Git Tag to deploy"
        required: false
        type: string

      deploy_branch:
        description: "Branch to deploy if no tag was provided"
        required: false
        type: string

  
jobs:
  set-deploying-artifact-and-dag-ids:
    runs-on: ubuntu-latest
    steps:

      - name: Validate inputs
        if: ${{ !github.event.inputs.deploy_tag && !github.event.inputs.deploy_branch }}
        run: |
          echo "Error: Either deploy_tag or deploy_branch must be provided."
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_tag || github.event.inputs.deploy_branch }}

      - name: Select git reference to deploy
        run: |
          echo "Selected git reference: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          DEPLOY_TAG=${{ github.event.inputs.deploy_tag }}
            
          if [[ "$DEPLOY_TAG" != "" ]]; then
            echo "DAG IDs will be concatenated with tag: $DEPLOY_TAG"
            echo "dags_concat_id=$DEPLOY_TAG" >> $GITHUB_OUTPUT
          
          else
            SHORTSHA=$(git rev-parse --short ${{ github.sha }})
            echo "Will deploy latest changes at branch: ${{ github.event.inputs.deploy_branch }}"
            echo "DAG IDs will be concatenated with short SHA from commit: $SHORTSHA"
            echo "dags_concat_id=$SHORTSHA" >> $GITHUB_OUTPUT
          fi