name: Build with Workload ID Federation

on:
  push:
    branches: [ "dev" ]

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Retrieve variables from master.json
      uses: ./.github/actions/master-variables
      id: master_variables

    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.base_ref}}" == ${{ steps.master_variables.outputs.environment }}-* || "${{github.ref}}" == refs/heads/${{ steps.master_variables.outputs.environment }}-* ]]; then
          echo "ACTION=plan" >> $GITHUB_ENV
          exit 0
        fi
        if [[ "${{github.base_ref}}" == "${{ steps.master_variables.outputs.environment }}" || "${{github.ref}}" == "refs/heads/${{ steps.master_variables.outputs.environment }}" ]]; then
          echo "ACTION=apply" >> $GITHUB_ENV
          exit 0
        fi
        echo "Base branch either does not match main (${{ steps.master_variables.outputs.environment }}) or is not a feature branch prefixed with ${{ steps.master_variables.outputs.environment }}"
        exit 1

    - name: Google Cloud Auth 
      id: auth
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
        service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

    - name: set credentials file
      shell: bash
      run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

    - name: Get Changed files 
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        dir_names: false
        files: dags/**

    - name: Install utilities
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        if ! command -v zip &> /dev/null; then
          echo "Zip not found, installing..." \
          sudo apt-get update \
          && sudo apt-get install zip -y
        fi

    - name: List updated JSON Files
      id: json_files
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        echo "${ALL_CHANGED_FILES}" | tr ' ' '\n' | awk -F'/' '{print $2}' | sort -u > changed-dirs.txt
        cat changed-dirs.txt
        JSON_LIST=$(cat changed-dirs.txt | tr '\n' ' ')
        echo "JSON_FILES=$JSON_LIST" >> $GITHUB_ENV  

    - name: Parse JSON and unzip DAG
      id: parse_json_and_unzip
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        cd dags
        for FILE in ${{ env.JSON_FILES }}; do
          dagname=$(jq -r '.dag_name' "$FILE") 
          dagversion=$(jq -r '.version' "$FILE")
          if [ -z "$dagname" ]; then
              echo "Error: Dagname not found in JSON file"
              exit 1
          fi
          if [ -z "$dagversion" ]; then
              echo "Error: Dagversion not found in JSON file"
              exit 1
          fi
          if [[ "${{ steps.master_variables.outputs.environment }}" != "dev" && ! "$dagversion" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9_-]+\.[0-9]+)?$ ]]; then
            echo "Environment is not dev, please provide the required tag for dagname: '$dagname'"
            echo "================ Skipping the above Dag File =============="
          else
            zip_file="${dagname}_${dagversion}.zip"

            TEMP_DIR="${dagname}_dir"
            echo "List composer artifacts to be downloaded: $zip_file"
          fi
          echo " $dagname " >> $GITHUB_STEP_SUMMARY 
          echo " $dagversion " >> $GITHUB_STEP_SUMMARY
        done
        
    - name: Add details to job summary
      shell: bash
      run: |
        echo " ${{ env.JSON_FILES }}  " >> $GITHUB_STEP_SUMMARY
