name: Build with Workload ID Federation

on:
  push:
    branches: [ "original" ]

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Retrieve variables from master.json
      uses: ./.github/actions/master-variables
      id: master_variables

    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.base_ref}}" == ${{ steps.master_variables.outputs.environment }}-* || "${{github.ref}}" == refs/heads/${{ steps.master_variables.outputs.environment }}-* ]]; then
          echo "ACTION=plan" >> $GITHUB_ENV
          exit 0
        fi
        if [[ "${{github.base_ref}}" == "${{ steps.master_variables.outputs.environment }}" || "${{github.ref}}" == "refs/heads/${{ steps.master_variables.outputs.environment }}" ]]; then
          echo "ACTION=apply" >> $GITHUB_ENV
          exit 0
        fi
        echo "Base branch either does not match main (${{ steps.master_variables.outputs.environment }}) or is not a feature branch prefixed with ${{ steps.master_variables.outputs.environment }}"
        exit 1

    - name: Add details to job summary
      shell: bash
      run: |
        echo " Variable: ${{github.base_ref}} * ${{github.ref}}  " >> $GITHUB_STEP_SUMMARY
