name: Composer CI Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        default: dev
        type: choice
        options:
          - dev
          - qa
          - stg
          - prd
      dags_to_deploy:
        description: "Specify the files for re-deployment. Use * to process all files or use commas to separate multiple file names. For example: file1,file2"
        required: true
        type: string

jobs:
  deploy-new-versions:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
      
    runs-on: ubuntu-latest
    
    steps:

      - name: Validate input parameters
        id: validate-deploy-inputs
        run: |
          
          DAGS_TO_DEPLOY=${{ github.event.inputs.dags_to_deploy }}

          if [[ "$DAGS_TO_DEPLOY" == "*" ]]; then
            echo "All DAGs will be deployed."
            echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> $GITHUB_OUTPUT

          else
            # Regex to validate the input string
            regex="^([a-zA-Z0-9_]+)(,[a-zA-Z0-9_]+)*$"

            if ! [[ "$DAGS_TO_DEPLOY" =~ $regex ]]; then
              echo "::error::Input string contains invalid characters or format. Only alphanumeric and underscore characters are allowed. Values must be comma-separated with no whitespaces."
              exit 1
            else
              echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> "$GITHUB_OUTPUT"
            fi

          fi
      
      - name: Take Git reference
        id: get-gitref
        run: |
          base=$(basename "${{ github.ref }}")
          sh_short=$(echo "${{ github.sha }}" | cut -c1-7)
        
          if [[ "${{ github.ref }}" == *"tags"* ]]; then
            ref="$base"
          else
            ref="$base-$sh_short"
          fi
          
          echo "git_ref=$ref" >> $GITHUB_OUTPUT
          echo "base_ref=$base" >> $GITHUB_OUTPUT

          echo "Git reference selected: ${{ github.ref }} " >> $GITHUB_STEP_SUMMARY


      - name: Checkout repository
        uses: actions/checkout@v4
        

      - id: auth
        name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"
 
      - name: set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"


      - name: New versions
        id: new-versions
        run: |
          
          echo "Fetching Airflow DAG Versions variable"
          FLAG_CREATE_DAGS_VS="false"
          CURRENT_DAGS_VS=$(gcloud composer environments run ${{ vars.COMPOSER_ENVIRONMENT_NAME }} --location=${{ vars.COMPOSER_REGION }} variables get -- dags_version 2>&1) || \
          CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines

          # Handle variable not existing sceneario
          if [[ "$CURRENT_DAGS_VS" == *"Variable dags_version does not exist"* ]]; then
            echo "::warning::Variable dags_version did not exist in Airflow environment. This process will recreate it. If this is not your first run review why it has been deleted."
            # Create var with dags vs being deployed
            
            FLAG_CREATE_DAGS_VS="true"

            echo "dags_version Airflow variable doesn't exist. It will be created. " >> $GITHUB_STEP_SUMMARY

          else
            CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines
            if [[ "$CURRENT_DAGS_VS" == *"{"*"}"* ]]; then # If response matches a JSON format {}
              echo "Found current DAGs version: $CURRENT_DAGS_VS" # Variable exists, get the output
            else
              echo "::error::gcloud command failed: $CURRENT_DAGS_VS" # gcloud command failed for a different reason
              exit 1
            fi
            echo "dags_version Airflow variable exists. It will be updated. " >> $GITHUB_STEP_SUMMARY
          fi


          # Get new version and files to process.
          DAG_ID_SUFFIX=${{ steps.get-gitref.outputs.git_ref }}
          echo "DAGs will be added suffix: $DAG_ID_SUFFIX"
          echo "DAGs new version will be: $DAG_ID_SUFFIX " >> $GITHUB_STEP_SUMMARY
          DAG_LIST=${{ steps.validate-deploy-inputs.outputs.dags_to_deploy }}
          echo "DAGs to deploy: $DAG_LIST"

          # Find path DAGs to process
          search_dir="$GITHUB_WORKSPACE/composer"
          found_dags=()
          found_dags_complete=()
          versioned_dags_to_deploy=()


          IFS=',' read -ra dags_to_deploy <<< "$DAG_LIST" # Convert comma-separated string to an array
          for item in "${dags_to_deploy[@]}"; do
            file=$(find composer/ -type f -name "$item.py")
            filename=$(basename "$file" .py)

            echo "$file"
            echo "$filename
          done

          





