name: Composer CI Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        default: dev
        type: choice
        options:
          - dev
          - qa
          - stg
          - prd
      dags_to_deploy:
        description: "Specify the files for re-deployment. Use * to process all files or use commas to separate multiple file names. For example: file1,file2"
        required: true
        type: string

jobs:
  deploy-new-versions:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
      
    runs-on: ubuntu-latest
    
    steps:

      - name: Validate input parameters
        id: validate-deploy-inputs
        run: |
          
          DAGS_TO_DEPLOY=${{ github.event.inputs.dags_to_deploy }}

          if [[ "$DAGS_TO_DEPLOY" == "*" ]]; then
            echo "All DAGs will be deployed."
            echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> $GITHUB_OUTPUT

          else
            # Regex to validate the input string
            regex="^([a-zA-Z0-9_]+)(,[a-zA-Z0-9_]+)*$"

            if ! [[ "$DAGS_TO_DEPLOY" =~ $regex ]]; then
              echo "::error::Input string contains invalid characters or format. Only alphanumeric and underscore characters are allowed. Values must be comma-separated with no whitespaces."
              exit 1
            else
              echo "dags_to_deploy=$DAGS_TO_DEPLOY" >> "$GITHUB_OUTPUT"
            fi

          fi
      
      - name: Take Git reference
        id: get-gitref
        run: |
          base=$(basename "${{ github.ref }}")
          sh_short=$(echo "${{ github.sha }}" | cut -c1-7)
        
          if [[ "${{ github.ref }}" == *"tags"* ]]; then
            ref="$base"
          else
            ref="$base-$sh_short"
          fi
          
          echo "git_ref=$ref" >> $GITHUB_OUTPUT
          echo "base_ref=$base" >> $GITHUB_OUTPUT

          echo "Git reference selected: ${{ github.ref }} " >> $GITHUB_STEP_SUMMARY


      - name: Checkout repository
        uses: actions/checkout@v4
        

      - id: auth
        name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"
 
      - name: set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"


      - name: New versions
        id: new-versions
        run: |
          
          echo "Fetching Airflow DAG Versions variable"
          FLAG_CREATE_DAGS_VS="false"
          CURRENT_DAGS_VS=$(gcloud composer environments run ${{ vars.COMPOSER_ENVIRONMENT_NAME }} --location=${{ vars.COMPOSER_REGION }} variables get -- dags_version 2>&1) || \
          CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines

          # Handle variable not existing sceneario
          if [[ "$CURRENT_DAGS_VS" == *"Variable dags_version does not exist"* ]]; then
            echo "::warning::Variable dags_version did not exist in Airflow environment. This process will recreate it. If this is not your first run review why it has been deleted."
            # Create var with dags vs being deployed
            
            FLAG_CREATE_DAGS_VS="true"

            echo "dags_version Airflow variable doesn't exist. It will be created. " >> $GITHUB_STEP_SUMMARY

          else
            CURRENT_DAGS_VS=$(echo "$CURRENT_DAGS_VS" | grep -v "Executing the command:" | grep -v "Command has been started." | grep -v "Use ctrl-c") # Remove the Airflow server non-relevant response lines
            if [[ "$CURRENT_DAGS_VS" == *"{"*"}"* ]]; then # If response matches a JSON format {}
              echo "Found current DAGs version: $CURRENT_DAGS_VS" # Variable exists, get the output
            else
              echo "::error::gcloud command failed: $CURRENT_DAGS_VS" # gcloud command failed for a different reason
              exit 1
            fi
            echo "dags_version Airflow variable exists. It will be updated. " >> $GITHUB_STEP_SUMMARY
          fi


          # Get new version and files to process.
          DAG_ID_SUFFIX=${{ steps.get-gitref.outputs.git_ref }}
          echo "DAGs will be added suffix: $DAG_ID_SUFFIX"
          echo "DAGs new version will be: $DAG_ID_SUFFIX " >> $GITHUB_STEP_SUMMARY
          DAG_LIST=${{ steps.validate-deploy-inputs.outputs.dags_to_deploy }}
          echo "DAGs to deploy: $DAG_LIST"

          # Find path DAGs to process
          search_dir="$GITHUB_WORKSPACE/composer"
          found_dags=()
          found_dags_complete=()
          versioned_dags_to_deploy=()


          if [[ "$DAG_LIST" == '*' ]]; then
            for file in $(find "$search_dir" -type f -path "*/dags/*.py"); do
              filename=$(basename "$file" .py)
              found_dags_complete+=("$file") # Append the found file to the array
              found_dags+=("$filename") # Append the found file complete path to the array
            done
          else
            IFS=',' read -ra dags_to_deploy <<< "$DAG_LIST" # Convert comma-separated string to an array
            for item in "${dags_to_deploy[@]}"; do
              file=$(find composer/ -type f -name "$item.py")
              filename=$(basename "$file" .py)
  
              found_dags_complete+=("$file") # Append the found file to the array
              found_dags+=("$filename") # Append the found file complete path to the array
            done
          fi


          echo "DAGs to update: ${versioned_dags_to_deploy[@]} " >> $GITHUB_STEP_SUMMARY
          
          # Iterate through the array of found dags to add deploy-specific ID
          if [[ ${#found_dags[@]} -gt 0 ]]; then
              for found_dag in "${found_dags[@]}"; do
                  versioned_dags_to_deploy+=("${found_dag}_${DAG_ID_SUFFIX}")
              done
          else
              echo "::error::No matching DAG files found. Review your repository files"
              exit 1
          fi


          echo "DAGs will be deployed as:"
          echo "${versioned_dags_to_deploy[@]}" # Space separated list


          # Create JSON string to update Airflow dags_version variable
          deploying_dags_json="{"
          for i in "${!found_dags[@]}"; do
            key="${found_dags[$i]}"
            value="${{ steps.get-gitref.outputs.git_ref }}"

            # Add comma separator (except for the last element)
            if [[ $i -lt $(( ${#found_dags[@]} - 1 )) ]]; then
              deploying_dags_json+="\"$key\":\"$value\","
            else
              deploying_dags_json+="\"$key\":\"$value\""
            fi
          done
          deploying_dags_json+="}"
          
          deploy_dags_jq=$(echo "$deploying_dags_json" | jq -c '.') # Convert JSON string to jq-readable format  


          if [[ "$FLAG_CREATE_DAGS_VS" == "true" ]]; then 
            echo "Creating dags_version var: $deploying_dags_json"
            gcloud composer environments run ${{ vars.COMPOSER_ENVIRONMENT_NAME }} --location=${{ vars.COMPOSER_REGION }} variables set -- dags_version "$deploying_dags_json"

          else
            echo "Updating dags_version var"
            current_dags_jq=$(echo "$CURRENT_DAGS_VS" | jq -c '.') # Convert JSON string to jq-readable format

            echo "Current DAGs versions: $current_dags_jq " >> $GITHUB_STEP_SUMMARY
            echo "Current DAGs Version (from Airflow): $current_dags_jq"
            echo "$current_dags_jq" > "current_version.json"

            echo "DAGs versions to update: $deploying_dags_json " >> $GITHUB_STEP_SUMMARY
            echo "New DAGs Version (from Workflow): $deploying_dags_json"
            echo "$deploying_dags_json" > "new_version.json"
            
            updated_dags_json=$(jq -s '.[0] * .[1]' current_version.json new_version.json)
            
            deploying_dags_json="$updated_dags_json" # Make this the unique JSON to work with going forward with this script

            gcloud composer environments run ${{ vars.COMPOSER_ENVIRONMENT_NAME }} --location=${{ vars.COMPOSER_REGION }} variables set -- dags_version "$deploying_dags_json"
            echo "DAGs new version file: $deploying_dags_json" >> $GITHUB_STEP_SUMMARY
          fi

          space_separated=$(IFS=' '; echo "${found_dags_complete[*]}")
          echo "dags_path=$space_separated" >> $GITHUB_OUTPUT

          versions_separated=$(IFS=' '; echo "${versioned_dags_to_deploy[*]}")
          echo "dag_new_versions=$versions_separated" >> $GITHUB_OUTPUT


      - name: Dags into GCP
        run: |
          DAG_VERSION=${{ steps.get-gitref.outputs.git_ref }}
          dags="${{ steps.new-versions.outputs.dags_path }}"
          for path in $dags; do
            file_name=$(basename "$path" .py)

            dagfile_content=$(cat "$path")

            dagfile_content=$(echo "$dagfile_content" | sed "s/dag_version *= *\"default\"/dag_version = \"$DAG_VERSION\"/g")

            echo "$dagfile_content" | gcloud storage cp - gs://${{ vars.COMPOSER_GCS_BUCKET }}/dags/${file_name}/dags/${file_name}.py

            echo "$path move into: ${{ vars.COMPOSER_GCS_BUCKET }} " >> $GITHUB_STEP_SUMMARY
          done


          
          





