name: Naming Convention

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path file to check version and update'
        required: true
        type: string
        default: "composer/groups/dags/groups.py"
      version:
        description: 'The new version to update (e.g., 1.2.3)'
        required: true
        type: string
        default: "1.0.1"
      tag:
        description: 'Tag name to create'
        required: false
        type: string
        default: ''

jobs:
  review:
    name: Review Execution
    runs-on: ubuntu-latest
    outputs:
      composer_environment_name: ${{ steps.master_variables.outputs.composer_environment_name }}
      composer_gcs_bucket: ${{ steps.master_variables.outputs.composer_gcs_bucket }}
      region: ${{ steps.master_variables.outputs.region }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Retrieve variables from master.json
      uses: ./.github/actions/master-variables
      id: master_variables

  increase-version:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: review

    steps:          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Read File
        run: |
          dag_version=$(python modify_dag_version.py "${{ github.event.inputs.path }}" "${{ github.event.inputs.version }}")
          
          echo "DAG version: $dag_version"
          
          data_content=$(cat "${{ github.event.inputs.path }}")
          echo "$data_content" >> $GITHUB_STEP_SUMMARY

      - name: Configure Git User
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit files
        run: |
          git add .
          git commit -m "GITHUB-ACTION: Update version DAG"
          
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            git tag ${{ github.event.inputs.tag }}
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          tags: ${{ inputs.create_tag != '' }}
