name: Count Python Files in DAGs

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      composer-gcs-bucket:
        description: "Bucket Composer environment"
        required: true
        default: "us-central1-instance-1833cf5d-bucket"
      composer-environment-name:
        description: "Name of Composer environment"
        required: true
        default: "instance"
      composer-location:
        description: "Name of Composer environment"
        required: true
        default: "us-central1"
        
jobs:
  count_python_files:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: auth
        name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

      - name: set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

      - name: Get Changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: false
          files: composer/**/dags/**/*.py

      - name: Get Version
        id: get-change
        if: steps.changed-files.outputs.any_changed
        run: |
          file_changed=${{ steps.changed-files.outputs.all_changed_files }}
          file_name=$(echo "${file_changed}" | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}')
          dag_version=$(python get_dag_version.py "$file_changed" "dag_version")
          new_version="${file_name}_${dag_version}"
          
          echo "dag_change=$file_changed" >> $GITHUB_OUTPUT
          echo "dag_new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Check DAGs Composer
        if: steps.changed-files.outputs.any_changed
        run: |
          POLL_PERIOD=5           # Poll every minute
          WHILE_TIMEOUT=$((60*15)) # 15 minutes
          ELAPSED=0                # Runtime

          deployed_dags=${{ steps.get-change.outputs.dag_new_version }}

          echo "$deployed_dags"

          while true; do
            
            # Check for timeout
            if [ "$ELAPSED" -ge "$WHILE_TIMEOUT" ]; then
              echo "State polling timed out."
              exit 1
            fi

            sleep $POLL_PERIOD
            ELAPSED=$((ELAPSED + POLL_PERIOD))
            
            composer_dags=$(gcloud composer environments run ${{ github.event.inputs.composer-environment-name }} --location=${{ github.event.inputs.composer-location }} dags list -- --output=json | jq "[.[] | select(.dag_id == \"$deployed_dags\")] | length ")
            
            if [[ "$composer_dags" -eq 0 ]]; then
              errors=$(gcloud composer environments run ${{ github.event.inputs.composer-environment-name }} --location=${{ github.event.inputs.composer-location }} dags list-import-errors -- --output=json)

              echo "$errors"
              
              if [[ -z "$errors" ]]; then
                echo "No import errors found. Continuing loop."
              else
                echo "Import errors found:"
                echo "$errors"
                echo "Send error ...."
                break
              fi
            else
              echo "DAG match. Exiting."
              break
            fi
            
          done
          
          


          
   
