name: Count Python Files in DAGs

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      composer-gcs-bucket:
        description: "Bucket Composer environment"
        required: true
        default: "us-central1-instance-1833cf5d-bucket"
      composer-environment-name:
        description: "Name of Composer environment"
        required: true
        default: "instance"
      composer-location:
        description: "Name of Composer environment"
        required: true
        default: "us-central1"
        
jobs:
  count_python_files:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: auth
        name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/979545525341/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc"
          service_account: "github-composer@telus-tir-project.iam.gserviceaccount.com"

      - name: set credentials file
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

      - name: Get Changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: false
          files: composer/**/dags/**/*.py

      - name: Get Version
        id: get-change
        if: steps.changed-files.outputs.any_changed
        run: |
          file_changed=${{ steps.changed-files.outputs.all_changed_files }}
          file_name=$(echo "${file_changed}" | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}')
          dag_version=$(python get_dag_version.py "$file_changed" "dag_version")
          new_version="${file_name}_${dag_version}"
          
          echo "dag_change=$file_changed" >> $GITHUB_OUTPUT
          echo "dag_new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Print
        if: steps.changed-files.outputs.any_changed
        run: |
          echo "${{ steps.get-change.outputs.dag_new_version }}"


          
   
