name: Capture Tag Value

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
        composer-gcs-bucket:
          description: "Bucket Composer environment"
          required: true
          default: "us-central1-instance-1833cf5d-bucket"
        composer-environment-name:
          description: "Name of Composer environment"
          required: true
          default: "instance"
        composer-location:
          description: "Name of Composer environment"
          required: true
          default: "us-central1"
          
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get Message 
        id: get-message
        run: |
          message=$(git log --format=%s -n 1 "$GITHUB_SHA" | tr '[:upper:]' '[:lower:]')
          echo "comm_message=$message" >> $GITHUB_OUTPUT

      - name: Set Condition
        id: set-condition
        run: |
          if [[ "${{ steps.get-message.outputs.comm_message }}" =~ ^github-action: ]]; then
            echo "skip_action=true" >> $GITHUB_OUTPUT
          else
            echo "skip_action=false" >> $GITHUB_OUTPUT
          fi

      - name: Get Changed files
        if: steps.set-condition.outputs.skip_action == 'false'
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: false
          files: composer/**/dags/**/*.py
      
      - name: Get DAG name
        id: get-change
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        run: |
          file_changed=${{ steps.changed-files.outputs.all_changed_files }}
          file_name=$(echo "${file_changed}" | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}')
          file_last_versions="dags_versions.json"
          echo "dag=$file_name" >> $GITHUB_OUTPUT
          echo "dag_path=$file_changed" >> $GITHUB_OUTPUT
          echo "file_version=$file_last_versions" >> $GITHUB_OUTPUT

      - name: Check Last Version and increment
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        id: set-new-version
        run: |
          last_version=$(jq -r ".${{ steps.get-change.outputs.dag }}" "${{ steps.get-change.outputs.file_version }}")

          echo "Current version: $last_version" >> $GITHUB_STEP_SUMMARY

          if [ "$last_version" == "null" ]; then
            new=1.0.0
          else
            major=$(echo "$last_version" | cut -d'.' -f1)
            minor=$(echo "$last_version" | cut -d'.' -f2)
            patchfix=$(echo "$last_version" | cut -d'.' -f3)
            
            kind_modification="${{ steps.get-message.outputs.comm_message }}"
            # kind_modification=$(echo "ENHANCE: blabla" | tr '[:upper:]' '[:lower:]')
          
            case "$kind_modification" in
              *fix*)
                echo "Kind: Fix" >> $GITHUB_STEP_SUMMARY
                patchfix=$((patchfix + 1))
                ;;
              *enhance*)
                echo "Kind: Enhancement" >> $GITHUB_STEP_SUMMARY
                minor=$((minor + 1))
                patchfix=0
                ;;
              *release*)
                echo "Kind: Release" >> $GITHUB_STEP_SUMMARY
                major=$((major + 1))
                minor=0
                patchfix=0
                ;;
              *)
                echo "Kind: Other or unknown" >> $GITHUB_STEP_SUMMARY 
                ;;
            esac
            
            new="$major.$minor.$patchfix"
          
          fi

          echo "New version: $new" >> $GITHUB_STEP_SUMMARY
          echo "new_version=$new" >> $GITHUB_OUTPUT
          
      - name: Update DAG Python File
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        run: |
          dag_version="${{ steps.set-new-version.outputs.new_version }}"
          dag_path="${{ steps.get-change.outputs.dag_path }}"

          python modify_dag_version.py "$dag_path" "$dag_version"

          data_content=$(cat $dag_path)

          echo "$data_content " >> $GITHUB_STEP_SUMMARY

      - name: Update Dags Last Versions
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        run: |
          json_file="${{ steps.get-change.outputs.file_version }}"
          dag_key=${{ steps.get-change.outputs.dag }}
          new_version=${{ steps.set-new-version.outputs.new_version }}

          jq_filter="has(\"$dag_key\")"
          key=$(jq $jq_filter $json_file)

          if [[ $key  = "true" ]]; then
            jq ".${{ steps.get-change.outputs.dag }} = \"$new_version\"" "$json_file" > temp.json && mv temp.json "$json_file"
          else
            jq --arg key "$dag_key" --arg value "$new_version" '. + { ($key): $value }' "$json_file" > temp.json && mv temp.json "$json_file"
          fi         
          
          # jq ".${{ steps.get-change.outputs.dag }} = \"${{ steps.set-new-version.outputs.new_version }}\"" "$json_file" > temp.json && mv temp.json "$json_file"
          json_content=$(cat $json_file)
          echo "$json_content " >> $GITHUB_STEP_SUMMARY

      - name: Configure Git User
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit files
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        run: |
          git add .
          git commit -m "GITHUB-ACTION: Update version DAG"

      - name: Push changes
        if: steps.changed-files.outputs.any_changed == 'true' && steps.set-condition.outputs.skip_action == 'false'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          tags: true

