name: Capture Tag Value

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  capture_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get Message 
        id: get-message
        run: |
          message=$(git log --format=%s -n 1 "$GITHUB_SHA" | tr '[:upper:]' '[:lower:]')
          echo "comm_message=$message" >> $GITHUB_OUTPUT

      - name: Set Condition
        id: set-condition
        run: |
          echo "A${{ steps.get-message.outputs.comm_message }}A" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ steps.get-message.outputs.comm_message }}" == *GITHUB-ACTION:* ]]; then
            echo "skip_action=true" >> $GITHUB_OUTPUT
            echo "Skip steps" >> $GITHUB_STEP_SUMMARY
          else
            echo "skip_action=false" >> $GITHUB_OUTPUT
            echo "No Skip steps" >> $GITHUB_STEP_SUMMARY
          fi

          
